### CLIENT
POST http://localhost:3333/client
Content-Type: application/json

{
  "username": "fabricyo",
  "password": "123456"
}
### DELIVERY
POST http://localhost:3333/delivery
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhYnJpY3lvIiwiaWF0IjoxNjY4MTI5NjMwLCJleHAiOjE2NjgyMTYwMzAsInN1YiI6IjJjM2E4NjA1LTVjOTItNDJkZS04OTBjLTkwMjc0ODI4OGVkYSJ9.7HE1rzlpZI-E8iftSZq3Ki1dyPx8KxBFkSEmB8c7I7s

{
  "item_name": "Batata Frita com coca cola"
}
###
GET http://localhost:3333/delivery/available
Content-Type: application/json
### AUTHENTICATE CLIENT
POST http://localhost:3333/client/authenticate
Content-Type: application/json

{
  "username": "fabricyo",
  "password": "123456"
}
### AUTHENTICATE DELIVERYMAN
POST http://localhost:3333/deliveryman/authenticate
Content-Type: application/json

{
  "username": "Lilian",
  "password": "123456"
}
### DELIVERYMAN
POST http://localhost:3333/deliveryman
Content-Type: application/json

{
  "username": "Lilian",
  "password": "123456"
}
