### CREATE CLIENT
POST http://localhost:3333/client
Content-Type: application/json

{
  "username": "fabricyo",
  "password": "123456"
}
### LIST CLIENT DELIVERIES
GET http://localhost:3333/client/deliveries
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhYnJpY3lvIiwiaWF0IjoxNjY4MTYzMjIyLCJleHAiOjE2NjgyNDk2MjIsInN1YiI6IjYxMmE0YmJmLTJlNGUtNDZhNS05MDJjLTVmODRlYTg2YmNmNSJ9.2hMYoEjQ6gNPRK7p_y6NFijnyuggjG9woGW5SaDxDRQ

### CREATE DELIVERY
POST http://localhost:3333/delivery
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhYnJpY3lvIiwiaWF0IjoxNjY4MTYyMjUwLCJleHAiOjE2NjgyNDg2NTAsInN1YiI6IjYxMmE0YmJmLTJlNGUtNDZhNS05MDJjLTVmODRlYTg2YmNmNSJ9.OvakLD6nIaCTgWNZr7AYL36MYVD07I0Iip965iqQqKg

{
  "item_name": "Mouse Gamer USB 3.0"
}
### LIST DELIVERIES
GET http://localhost:3333/delivery/available
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhYnJpY3lvIiwiaWF0IjoxNjY4MTI5NjMwLCJleHAiOjE2NjgyMTYwMzAsInN1YiI6IjJjM2E4NjA1LTVjOTItNDJkZS04OTBjLTkwMjc0ODI4OGVkYSJ9.7HE1rzlpZI-E8iftSZq3Ki1dyPx8KxBFkSEmB8c7I7s

### AUTHENTICATE CLIENT
POST http://localhost:3333/client/authenticate
Content-Type: application/json

{
  "username": "fabricyo",
  "password": "123456"
}
### AUTHENTICATE DELIVERYMAN
POST http://localhost:3333/deliveryman/authenticate
Content-Type: application/json

{
  "username": "Lilian",
  "password": "123456"
}
### LIST DELIVERYMAN DELIVERIES
GET http://localhost:3333/deliveryman/deliveries
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkxpbGlhbiIsImlhdCI6MTY2ODIwNzM2MywiZXhwIjoxNjY4MjkzNzYzLCJzdWIiOiIwZjgzZTIzMC05NWNjLTRmZjQtOGZiYS04MmRlM2NiMDlhN2UifQ.zmv0GJoO8pzCHqN6DWhP5p1vwOvMMldvcynaW6H866w
### UPDATE DELIVERYMAN DATE-END
PUT http://localhost:3333/delivery/update-end-date/4caa4a53-709c-4e19-9ec2-2ea7eaec8829
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkxpbGlhbiIsImlhdCI6MTY2ODIwNzM2MywiZXhwIjoxNjY4MjkzNzYzLCJzdWIiOiIwZjgzZTIzMC05NWNjLTRmZjQtOGZiYS04MmRlM2NiMDlhN2UifQ.zmv0GJoO8pzCHqN6DWhP5p1vwOvMMldvcynaW6H866w

### CREATE DELIVERYMAN
POST http://localhost:3333/deliveryman
Content-Type: application/json

{
  "username": "Lilian",
  "password": "123456"
}
### GET DELIVERY
PUT  http://localhost:3333/delivery/update-deliveryman/4caa4a53-709c-4e19-9ec2-2ea7eaec8829
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkxpbGlhbiIsImlhdCI6MTY2ODE2MjIwNSwiZXhwIjoxNjY4MjQ4NjA1LCJzdWIiOiIwZjgzZTIzMC05NWNjLTRmZjQtOGZiYS04MmRlM2NiMDlhN2UifQ.aUWykP3PXGu_bLhqQ8kKik_sJ2ly7qOPTfisZG-fZTA
